### PR TITLE
Split 0.7.0 yaml files into open and closed variants

### PR DESCRIPTION
**Pull request by davidmochen**
When division = open or closed, the open or closed yaml variant is
enqueued. The closed yaml files are branched from the previous yaml
files. The open yaml files have the hyperparameter checks removed and
only the accuracy checks retained.

Tested:
with some submission packages

### CODE REVIEW

**Comment by mwawrzos** [comment]
Please rename benchmarks YAMLs, to unify naming:
* bert.yaml -> open_bert.yaml
* resnet_lars.yaml -> open_resnet_lars.yaml
* etc.

I hope, git will notice, that files are renamed, not edited.

**Comment by davidmochen** [comment]
Thanks for the suggestion. Renamed <model>.yaml to open_<model>.yaml

**Comment by mwawrzos** [comment]
Thanks for the renaming. Now the diff looks much better!

Before the merge, can we add a tag, for example, `0.7.0-rc3-closed-division` on `4de7d97dc45abf39a511bf20a5364b32c3b963c1`?

It would make clear to closed division submitters, that new commits don't refer to them, and they can simply ignore new changes without checking if their submission is still compliant.

**Comment by davidmochen** [comment]
Sure, created a new tag 0.7.0-rc3-closed-division on 4de7d97dc45abf39a511bf20a5364b32c3b963c1:
https://github.com/mlperf/logging/releases

**Comment by mwawrzos** [comment]
LGTM

**Pull request merged**
